{{- if gt (len .Values.single.config.outputs.influxdb.urls) 0 }}
{{- if .Values.single.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-s
  labels:
    app: {{ template "fullname" . }}-s
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-s
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
        heritage: {{ .Release.Service }}
      annotations:
        productName: ibm-telegraf-dev
        productID: ibm-telegraf-dev_{{ .Chart.Version }}
        productVersion: {{ .Chart.Version }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "" .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: true
          runAsNonRoot: false
          runAsUser: 0
          capabilities:
           drop:
           - MKNOD
        livenessProbe:
          httpGet:
            path: /
            port: 8094
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8094
            initialDelaySeconds: 180
            timeoutSeconds: 5
            periodSeconds: 5
        resources:
{{ toYaml .Values.single.resources | indent 10 }}
        volumeMounts:
        - name: config
          #mountPath: /etc/telegraf
          mountPath: /root/go/src/github.com/influxdata/telegraf/etc/
      volumes:
      - name: config
        configMap:
          name: {{ template "fullname" . }}-s
{{- end -}}
{{- end -}}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}

