apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kaazinggateway.fullname" . }}
  labels:
    app: {{ template "kaazinggateway.name" . }}
    chart: {{ template "kaazinggateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kaazinggateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kaazinggateway.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "kaazinggateway.chart" . }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: rstudio
        productID: rstudio_{{ .Chart.Version }}
        productVersion: {{ .Chart.Version }}
    spec:
      hostname: kaazinggatway
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
             drop:
             - MKNOD
          env:
           - name: MY_POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name  
           - name: GATEWAY_OPTS
             value: {{ "-Dgateway.hostname=kaazinggatway -Xmx512m -Djava.security.egd=file:/dev/urandom" }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:                  ##Added but do not work.
            httpGet:
              path: /amqp
              port: http
              initialDelaySeconds: 180
              timeoutSeconds: 5
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /echo
              port: http
              initialDelaySeconds: 180
              timeoutSeconds: 5
              periodSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}
