{{- if .Values.deployments.restoreOperator }}

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "etcd-restore-operator.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "etcd-restore-operator.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.restoreOperator.replicaCount }}
  template:
    metadata:
      name: {{ template "etcd-restore-operator.fullname" . }}
      labels:
        app: {{ template "etcd-restore-operator.name" . }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: etcd-restore-operator
        productID: etcd-restore-operator_{{ .Chart.Version }}
        productVersion: {{ .Chart.Version }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ template "etcd-restore-operator.serviceAccountName" . }}
      containers:
      - name: {{ .Values.restoreOperator.name }}
        image: "{{ .Values.restoreOperator.image.repository }}:{{ .Values.restoreOperator.image.tag }}"
        imagePullPolicy: {{ .Values.restoreOperator.image.pullPolicy }}
        securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
             drop:
             - MKNOD 
        ports:
        - containerPort: {{ .Values.restoreOperator.port }}
        command:
        - /usr/local/bin/etcd
{{- range $key, $value := .Values.restoreOperator.commandArgs }}
        - "--{{ $key }}={{ $value }}"
{{- end }}
        livenessProbe:
           httpGet:
             path: /
             port: 2380
           initialDelaySeconds: {{ .Values.etcdOperator.readinessProbe.initialDelaySeconds }}
           periodSeconds: {{ .Values.etcdOperator.readinessProbe.periodSeconds }}
           timeoutSeconds: {{ .Values.etcdOperator.readinessProbe.timeoutSeconds }}
           successThreshold: {{ .Values.etcdOperator.readinessProbe.successThreshold }}
           failureThreshold: {{ .Values.etcdOperator.readinessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /
            port: 2380
          initialDelaySeconds: {{ .Values.etcdOperator.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.etcdOperator.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.etcdOperator.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.etcdOperator.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.etcdOperator.readinessProbe.failureThreshold }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: "{{ .Values.restoreOperator.name }}:{{ .Values.restoreOperator.port }}"
        resources:
          limits:
            cpu: {{ .Values.restoreOperator.resources.cpu }}
            memory: {{ .Values.restoreOperator.resources.memory }}
          requests:
            cpu: {{ .Values.restoreOperator.resources.cpu }}
            memory: {{ .Values.restoreOperator.resources.memory }}
    {{- if .Values.restoreOperator.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.restoreOperator.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.restoreOperator.tolerations }}
      tolerations:
{{ toYaml .Values.restoreOperator.tolerations | indent 8 }}
    {{- end }}
{{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}
