appVersion: "1.5"
kubeVersion: ">=1.10.0"
deprecated: true
description: Telegraf is an agent for processing metrics.
engine: gotpl
home: https://www.influxdata.com/time-series-platform/telegraf/
icon: https://raw.githubusercontent.com/ppc64le/charts/master/logo/telegraf.png
keywords:
- telegraf
- collector
- timeseries
- influxdata
- Limited
- ppc64le
- Tools
- ICP
- Beta

maintainers:
- email: smohite@us.ibm.com
  name: IBM ISV Team
name: ibm-telegraf-dev
version: 0.3.3
tillerVersion: '>=2.7.2'
