apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tidb.fullname" . }}
  labels:
    app: {{ template "tidb.name" . }}
    chart: {{ template "tidb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "tidb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "tidb.name" . }}
        release: {{ .Release.Name }}
        chart: {{ template "tidb.chart" . }}
        heritage: {{ .Release.Service }}
      annotations:
        productName: tidb
        productID: tidb_{{ .Chart.Version }}
        productVersion: {{ .Chart.Version }}
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
             drop:
             - MKNOD
          command: ["tidb-server"]
          ports:
            - name: tidbport
              containerPort: 4000
          livenessProbe:
            httpGet:
              path: /
              port: tidbport
              initialDelaySeconds: 180
              timeoutSeconds: 5
              periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: tidbport
              initialDelaySeconds: 180
              timeoutSeconds: 5
              periodSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.node }}
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
{{- end }}

